package com.ynotlabs.cathopedia.stations

/**
 * One of the 14 traditional Stations of the Cross. Titles are standard
 * devotional labels (like a category name, not quoted prayer text) so they
 * ship directly as plain Kotlin strings; meditation/versicle/response are
 * real prayer text sourced from a real citable publication -- see
 * content/stations/<slug>.json for the full citation backing each field.
 * English: St. Alphonsus de Liguori's "Way of the Cross" (eCatholic2000.com).
 * French: spiritualite-chretienne.com (archived) + Diocese de Saint-Etienne,
 * provisional pending AELF licence per content/README.md's convention.
 */
data class Station(
    val number: Int,
    val id: String,
    val titleEn: String,
    val titleFr: String,
    val meditationEn: String,
    val meditationFr: String,
    val versicleEn: String,
    val responseEn: String,
    val versicleFr: String,
    val responseFr: String,
)

object StationsData {
    val stations: List<Station> = listOf(
        Station(
            number = 1,
            id = "01-jesus-condemned-to-death",
            titleEn = "Jesus is Condemned to Death",
            titleFr = "Jésus est condamné à mort",
            meditationEn = "Consider how Jesus, after having been scourged and crowned with thorns, was unjustly condemned by Pilate to die on the Cross.\n\nMy adorable Jesus, it was not Pilate, no, it was my sins that condemned Thee to die. I beseech Thee, by the merits of this sorrowful journey, to assist my soul in its journey towards eternity. I love Thee, my beloved Jesus; I repent with my whole heart for having offended Thee. Never permit me to separate myself from Thee again. Grant that I may love Thee always; and then do with me what Thou wilt.",
            meditationFr = "Considérons comment après avoir été flagellé et couronné d’épines, Jésus-Christ est injustement condamné à mourir crucifié, par un juge qui s’en lavait les mains, bien convaincu de l’innocence de sa Victime.\n\nJe songe, ô mon adorable Jésus, que ce ne fut pas Pilate, par sa lâcheté, qui vous livra à la mort. Ce sont plutôt mes péchés qui Vous condamnèrent, puisque pour me sauver, Vous avez pris sur Vous toutes mes iniquités.",
            versicleEn = "We adore Thee, O Christ, and we bless Thee.",
            responseEn = "Because by Thy holy Cross, Thou hast redeemed the world.",
            versicleFr = "Nous t’adorons, ô Christ, et nous te bénissons,",
            responseFr = "parce que tu as racheté le monde par ta sainte Croix.",
        ),
        Station(
            number = 2,
            id = "02-jesus-carries-his-cross",
            titleEn = "Jesus Carries His Cross",
            titleFr = "Jésus est chargé de la croix",
            meditationEn = "Consider how Jesus, in making this journey with the Cross on His shoulders thought of us, and for us offered to His Father the death He was about to undergo.\n\nMy most beloved Jesus, I embrace all the tribulations Thou hast destined for me until death. I beseech Thee, by the merits of the pain Thou didst suffer in carrying Thy Cross, to give me the necessary help to carry mine with perfect patience and resignation. I love Thee, Jesus my love; I repent of having offended Thee. Never permit me to separate myself from Thee again. Grant that I may love Thee always; and then do with me what Thou wilt.",
            meditationFr = "Considérons comment, tout en montant péniblement sur la montagne du Calvaire, avec la croix sur ses épaules, Jésus-Christ pensait à nous, et offrait pour nous à Dieu la mort qu’Il s’en allait souffrir.\n\nO mon très aimable Jésus, au souvenir des douleurs endurées en portant Votre croix, je veux, fortifié par Votre grâce, accepter avec patience toutes les peines qu’Il Vous plaira de me faire supporter.",
            versicleEn = "We adore Thee, O Christ, and we bless Thee.",
            responseEn = "Because by Thy holy Cross, Thou hast redeemed the world.",
            versicleFr = "Nous t’adorons, ô Christ, et nous te bénissons,",
            responseFr = "parce que tu as racheté le monde par ta sainte Croix.",
        ),
        Station(
            number = 3,
            id = "03-jesus-falls-the-first-time",
            titleEn = "Jesus Falls the First Time",
            titleFr = "Jésus tombe une première fois",
            meditationEn = "Consider this first fall of Jesus under His Cross. His flesh was torn by the scourges, His head crowned with thorns, and He had lost a great quantity of blood. He was so weakened that he could scarcely walk, and yet he had to carry this great load upon His shoulders. The soldiers struck Him rudely, and thus He fell several times in His journey.\n\nMy beloved Jesus, it is not the weight of the Cross, but my sins, which have made Thee suffer so much pain. Ah, by the merits of this first fall, deliver me from the misfortune of falling into mortal sin. I love Thee, O my Jesus, with my whole heart; I repent of having offended Thee. Never permit me to separate myself from Thee again. Grant that I may love Thee always; and then do with me what Thou wilt.",
            meditationFr = "Considérons cette première chute de Jésus-Christ sous la croix. Ses chairs déchirées par les fouets, sa tête couronnée d’épines, son sang répandu en grande quantité, l’avaient réduit à une si extrême faiblesse qu’Il pouvait à peine marcher, et cependant, les soldats le poussaient durement. Tout cela fit qu’Il tomba à plusieurs reprises sur le chemin.\n\nMon bien-aimé Jésus, par le mérite de cette première chute, préservez-moi de tomber dans le péché mortel et même de m’attacher par habitude à quelque péché véniel.",
            versicleEn = "We adore Thee, O Christ, and we bless Thee.",
            responseEn = "Because by Thy holy Cross, Thou hast redeemed the world.",
            versicleFr = "Nous t’adorons, ô Christ, et nous te bénissons,",
            responseFr = "parce que tu as racheté le monde par ta sainte Croix.",
        ),
        Station(
            number = 4,
            id = "04-jesus-meets-his-mother",
            titleEn = "Jesus Meets His Mother",
            titleFr = "Jésus rencontre sa mère affligée",
            meditationEn = "Consider the meeting of the Son and the Mother, which took place on this journey. Jesus and Mary looked at each other, and their looks became as so many arrows to wound those hearts which loved each other so tenderly.\n\nMy most loving Jesus, by the sorrow Thou didst experience in this meeting, grant me the grace of a truly devoted love for Thy most holy Mother. And thou, my Queen, who wast overwhelmed with sorrow, obtain for me by thy intercession a continual and tender remembrance of the Passion of thy Son. I love Thee, Jesus my love; I repent of ever having offended Thee. Never permit me to offend Thee again. Grant that I may love Thee always; and then do with me what Thou wilt.",
            meditationFr = "Considérons la rencontre du Fils et de la Mère sur le chemin douloureux. Jésus et Marie se regardent, et leurs regards sont comme autant de traits qui percent réciproquement leurs cœurs brûlants d’un mutuel amour.\n\nTrès aimant Jésus, par la peine que vous avez ressentie, dans cette rencontre, accordez-moi la grâce d’être un vrai serviteur de votre très Sainte Mère, et d’avoir en Elle une grande confiance.",
            versicleEn = "We adore Thee, O Christ, and we bless Thee.",
            responseEn = "Because by Thy holy Cross, Thou hast redeemed the world.",
            versicleFr = "Nous t’adorons, ô Christ, et nous te bénissons,",
            responseFr = "parce que tu as racheté le monde par ta sainte Croix.",
        ),
        Station(
            number = 5,
            id = "05-simon-of-cyrene-helps-jesus-carry-the-cross",
            titleEn = "Simon of Cyrene Helps Jesus Carry the Cross",
            titleFr = "Jésus reçoit l’aide du Cyrénéen",
            meditationEn = "Consider how the Jews, seeing that at each step Jesus from weakness was on the point of expiring, and fearing that He would die on the way, when they wished Him to die the ignominious death of the Cross, constrained Simon the Cyrenian to carry the Cross behind our Lord.\n\nMy most sweet Jesus, I will not refuse the Cross, as the Cyrenian did; I accept it; I embrace it. I accept in particular the death Thou hast destined for me; with all the pains that may accompany it; I unite it to Thy death, I offer it to Thee. Thou hast died for love of me; I will die for love of Thee, and to please Thee. Help me by Thy grace. I love Thee, Jesus my love; I repent of having offended Thee. Never permit me to offend Thee again. Grant that I may love Thee always; and then do with me what Thou wilt.",
            meditationFr = "Considérons comment les Juifs, voyant que Jésus dans son extrême faiblesse était sur le point d’expirer, craignirent qu’Il ne mourût en chemin, sans mourir de la mort infâme de la croix. C’est pourquoi ils contraignirent Simon le Cyrénéen à porter la croix après Notre-Seigneur.\n\nMon très doux Jésus, je ne veux pas hésiter, comme le Cyrénéen, et j’accepte spécialement pour l’amour de Vous, la mort qui m’est réservée, avec les peines qui doivent l’accompagner. Je l’unis à Votre mort et je Vous l’offre.",
            versicleEn = "We adore Thee, O Christ, and we bless Thee.",
            responseEn = "Because by Thy holy Cross, Thou hast redeemed the world.",
            versicleFr = "Nous t’adorons, ô Christ, et nous te bénissons,",
            responseFr = "parce que tu as racheté le monde par ta sainte Croix.",
        ),
        Station(
            number = 6,
            id = "06-veronica-wipes-the-face-of-jesus",
            titleEn = "Veronica Wipes the Face of Jesus",
            titleFr = "Véronique essuie la Sainte Face de Jésus",
            meditationEn = "Consider how the holy woman named Veronica, seeing Jesus so afflicted, and His face bathed in sweat and blood, presented Him with a towel, with which He wiped His adorable face, leaving on it the impression of His holy countenance.\n\nMy most beloved Jesus, Thy face was beautiful before, but in this journey it has lost all its beauty, and wounds and blood have disfigured it. Alas, my soul also was once beautiful, when it received Thy grace in Baptism; but I have disfigured it since by my sins; Thou alone, my Redeemer, canst restore it to its former beauty. Do this by Thy Passion, O Jesus. I repent of having offended Thee. Never permit me to offend Thee again. Grant that I may love Thee always; and then do with me what Thou wilt.",
            meditationFr = "Considérons comment une sainte femme, nommée Véronique, voyant Jésus excédé de douleur, le visage inondé de sueur et de sang, lui présente un linge sur lequel Notre-Seigneur, en s’essuyant, imprime l’image de ses traits sacrés.\n\nMon très aimé Jésus, pendant Votre passion, le sang qui coulait de Vos blessures avait altéré la beauté de Votre visage. Hélas ! mon âme aussi était belle à mon Baptême, malheureusement je l’ai enlaidie par mes péchés. Vous seul, mon divin Rédempteur, pouvez lui rendre sa beauté ; faites-le, je vous en conjure, par votre passion.",
            versicleEn = "We adore Thee, O Christ, and we bless Thee.",
            responseEn = "Because by Thy holy Cross, Thou hast redeemed the world.",
            versicleFr = "Nous t’adorons, ô Christ, et nous te bénissons,",
            responseFr = "parce que tu as racheté le monde par ta sainte Croix.",
        ),
        Station(
            number = 7,
            id = "07-jesus-falls-the-second-time",
            titleEn = "Jesus Falls the Second Time",
            titleFr = "Jésus tombe pour la deuxième fois",
            meditationEn = "Consider the second fall of Jesus under the Cross—a fall which renews the pain of all the wounds of the head and members of our afflicted Lord.\n\nMy most gentle Jesus, how many times Thou hast pardoned me, and how many times have I fallen again, and begun again to offend Thee! Oh, by the merits of this new fall, give me the necessary help to persevere in Thy grace until death. Grant that in all temptations which assail me I may always commend myself to Thee. I love Thee, Jesus my love; I repent of having offended Thee. Never permit me to offend Thee again. Grant that I may love Thee always; and then do with me what Thou wilt.",
            meditationFr = "Considérons cette deuxième chute de Jésus sous la croix ; elle renouvelle la douleur de toutes ses blessures du chef adorable et des autres membres sacrés de notre très affligé Seigneur.\n\nO Jésus, plein de mansuétude, que de fois Vous m’avez pardonné, et toujours je suis retombé en Vous offensant à nouveau. Faites que, dans toutes les tentations, je me recommande plus promptement à Vous, pour ne pas succomber.",
            versicleEn = "We adore Thee, O Christ, and we bless Thee.",
            responseEn = "Because by Thy holy Cross, Thou hast redeemed the world.",
            versicleFr = "Nous t’adorons, ô Christ, et nous te bénissons,",
            responseFr = "parce que tu as racheté le monde par ta sainte Croix.",
        ),
        Station(
            number = 8,
            id = "08-jesus-meets-the-women-of-jerusalem",
            titleEn = "Jesus Meets the Women of Jerusalem",
            titleFr = "Jésus adresse la parole aux femmes de Jérusalem",
            meditationEn = "Consider how those women wept with compassion at seeing Jesus in such a pitiable state, streaming with blood, as He walked along. But Jesus said to them: Weep not for Me, but for your children.\n\nMy Jesus, laden with sorrows, I weep for the offences I have committed against Thee, because of the pains they have deserved, and still more because of the displeasure they have caused Thee, who hast loved me so much. It is Thy love, more than the fear of hell, which causes me to weep for my sins. My Jesus, I love Thee more than myself; I repent of having offended Thee. Never permit me to offend Thee again. Grant that I may love Thee always; and then do with me what Thou wilt.",
            meditationFr = "Considérons comment à la vue de Jésus si maltraité et arrosant le chemin de son sang, les femmes pleuraient de compassion : « Ne pleurez pas sur moi » leur dit Jésus ; « mais pleurez sur vous-mêmes et sur vos enfants. »\n\nMon Jésus accablé de douleurs, je regrette les offenses que je Vous ai faites, à cause des châtiments que j’ai mérités ; mais surtout à cause de la peine que je vous ai causée, à Vous qui m’avez tant aimé.",
            versicleEn = "We adore Thee, O Christ, and we bless Thee.",
            responseEn = "Because by Thy holy Cross, Thou hast redeemed the world.",
            versicleFr = "Nous t’adorons, ô Christ, et nous te bénissons,",
            responseFr = "parce que tu as racheté le monde par ta sainte Croix.",
        ),
        Station(
            number = 9,
            id = "09-jesus-falls-the-third-time",
            titleEn = "Jesus Falls the Third Time",
            titleFr = "Jésus tombe une troisième fois",
            meditationEn = "Consider the third fall of Jesus Christ. His weakness was extreme, and the cruelty of His executioners was excessive, who tried to hasten His steps when He had scarcely strength to move.\n\nAh, my outraged Jesus, by the merits of the weakness Thou didst suffer in going to Calvary, give me strength sufficient to conquer all human respect, and all my wicked passions, which have led me to despise Thy friendship. I love Thee, Jesus my love, with my whole heart; I repent of having offended Thee. Never permit me to offend Thee again. Grant that I may love Thee always; and then do with me what Thou wilt.",
            meditationFr = "Considérons la troisième chute de Jésus. Sa faiblesse était excessive et excessive était la cruauté des bourreaux, qui voulaient lui faire hâter le pas, alors qu’Il avait à peine encore la force d’avancer.\n\nMon Jésus abreuvé d’outrages, par le mérite de cette faiblesse que Vous avez bien voulu éprouver, en allant au Calvaire, donnez-moi la force de vaincre celui de mes penchants mauvais qui semble être la cause ordinaire de mes chutes.",
            versicleEn = "We adore Thee, O Christ, and we bless Thee.",
            responseEn = "Because by Thy holy Cross, Thou hast redeemed the world.",
            versicleFr = "Nous t’adorons, ô Christ, et nous te bénissons,",
            responseFr = "parce que tu as racheté le monde par ta sainte Croix.",
        ),
        Station(
            number = 10,
            id = "10-jesus-is-stripped-of-his-garments",
            titleEn = "Jesus is Stripped of His Garments",
            titleFr = "Jésus est dépouillé de ses vêtements",
            meditationEn = "Consider the violence with which the executioners stripped Jesus. His inner garments adhered to His torn flesh, and they dragged them off so roughly that the skin came with them.\n\nMy innocent Jesus, by the merits of the torment Thou hast felt, help me to strip myself of all affection to things of earth, in order that I may place all my love in Thee, who art so worthy of my love. I love Thee, O Jesus, with my whole heart; I repent of having offended Thee. Never permit me to offend Thee again. Grant that I may love Thee always; and then do with me what Thou wilt.",
            meditationFr = "Considérons avec quelle violence les bourreaux dépouillent Jésus : son vêtement intérieur était collé à ses chairs déchirées par les fouets ; en le lui arrachant, ils lui arrachent aussi la peau, au milieu d’horribles souffrances.\n\nMon Jésus innocent, par le mérite des douleurs que Vous avez ressenties alors, aidez-moi à me dépouiller de toute affection qui ne serait pas vraiment chrétienne.",
            versicleEn = "We adore Thee, O Christ, and we bless Thee.",
            responseEn = "Because by Thy holy Cross, Thou hast redeemed the world.",
            versicleFr = "Nous t’adorons, ô Christ, et nous te bénissons,",
            responseFr = "parce que tu as racheté le monde par ta sainte Croix.",
        ),
        Station(
            number = 11,
            id = "11-jesus-is-nailed-to-the-cross",
            titleEn = "Jesus is Nailed to the Cross",
            titleFr = "Jésus est cloué à la croix",
            meditationEn = "Consider how Jesus, after being thrown on the Cross extended His hands, and offered to His Eternal Father the sacrifice of His death for our salvation. These barbarians fastened Him with nails, and then, raising the Cross, allowed Him to die with anguish on this infamous gibbet.\n\nMy Jesus! loaded with contempt, nail my heart to Thy feet, that it may ever remain there, to love Thee, and never quit Thee again. I love Thee more than myself; I repent of having offended Thee. Never permit me to offend Thee again. Grant that I may love Thee always; and then do with me what Thou wilt.",
            meditationFr = "Considérons comment Jésus, renversé sur la croix, étend les mains et offre au Père éternel le sacrifice de sa vie pour notre salut. Ces bourreaux l’attachent avec des clous, élèvent ensuite la croix, et le font mourir sur ce cruel et infâme gibet.\n\nMon Jésus outragé, placez mon cœur tout près du Vôtre, afin qu’il n’oublie jamais Votre amour et ne cesse jamais de Vous aimer.",
            versicleEn = "We adore Thee, O Christ, and we bless Thee.",
            responseEn = "Because by Thy holy Cross, Thou hast redeemed the world.",
            versicleFr = "Nous t’adorons, ô Christ, et nous te bénissons,",
            responseFr = "parce que tu as racheté le monde par ta sainte Croix.",
        ),
        Station(
            number = 12,
            id = "12-jesus-dies-on-the-cross",
            titleEn = "Jesus Dies on the Cross",
            titleFr = "Jésus meurt sur la croix",
            meditationEn = "Consider how thy Jesus, after three hours’ Agony on the Cross, consumed at length with anguish, abandons Himself to the weight of His body, bows His head, and dies.\n\nO my dying Jesus, I kiss devoutly the Cross on which Thou didst die for love of me. I have merited by my sins to die a miserable death; but Thy death is my hope. Ah, by the merits of Thy death, give me grace to die, embracing Thy feet, and burning with love for Thee. I yield my soul into Thy hands. I love Thee with my whole heart; I repent of ever having offended Thee. Never permit me to offend Thee again. Grant that I may love Thee always; and then do with me what Thou wilt.",
            meditationFr = "Considérons comment, après trois heures d’agonie sur la croix, Jésus meurt épuisé enfin par les douleurs, s’affaisse, incline la tête et meurt.\n\nO mon Jésus, j’embrasse avec attendrissement cette croix sur laquelle Vous êtes mort pour moi. Et quand viendra l’heure de ma mort, permettez-moi de Vous donner un dernier baiser sur le Crucifix.",
            versicleEn = "We adore Thee, O Christ, and we bless Thee.",
            responseEn = "Because by Thy holy Cross, Thou hast redeemed the world.",
            versicleFr = "Nous t’adorons, ô Christ, et nous te bénissons,",
            responseFr = "parce que tu as racheté le monde par ta sainte Croix.",
        ),
        Station(
            number = 13,
            id = "13-jesus-is-taken-down-from-the-cross",
            titleEn = "Jesus is Taken Down from the Cross",
            titleFr = "Jésus est descendu de la croix",
            meditationEn = "Consider how, after the death of our Lord, two of His disciples, Joseph and Nicodemus, took Him down from the Cross, and placed Him in the arms of His afflicted Mother, who received Him with unutterable tenderness, and pressed Him to her bosom.\n\nO Mother of sorrow, for the love of this Son, accept me for thy servant, and pray to Him for me. And Thou, my Redeemer, since Thou hast died for me, permit me to love Thee; for I wish but Thee, and nothing more. I love Thee, my Jesus, and I repent of ever having offended Thee. Never permit me to offend Thee again. Grant that I may love Thee always; and then do with me what Thou wilt.",
            meditationFr = "Considérons comment, après la mort du Seigneur, deux de ses disciples : Joseph et Nicodème, le descendent de la croix et le remettent entre les bras de la Très Sainte Vierge, sa Mère affligée qu’accompagnait saint Jean.\n\nO mon divin Rédempteur, à l’exemple de Votre Sainte Mère, faites que j’aie le courage de participer à Votre sacrifice de réparation pour le salut des âmes, en prenant part aux bonnes œuvres et en faisant quelques pénitences.",
            versicleEn = "We adore Thee, O Christ, and we bless Thee.",
            responseEn = "Because by Thy holy Cross, Thou hast redeemed the world.",
            versicleFr = "Nous t’adorons, ô Christ, et nous te bénissons,",
            responseFr = "parce que tu as racheté le monde par ta sainte Croix.",
        ),
        Station(
            number = 14,
            id = "14-jesus-laid-in-the-tomb",
            titleEn = "Jesus is Laid in the Tomb",
            titleFr = "Jésus est mis dans le sépulcre",
            meditationEn = "Consider how the disciples carried the body of Jesus to bury it, accompanied by His holy Mother, who arranged it in the sepulchre with her own hands. They then closed the tomb, and all withdrew.\n\nOh, my buried Jesus, I kiss the stone that encloses Thee. But Thou didst rise again the third day. I beseech Thee, by Thy resurrection, make me rise glorious with Thee at the last day, to be always united with Thee in heaven, to praise Thee and love Thee forever. I love Thee, and I repent of ever having offended Thee. Never permit me to offend Thee again. Grant that I may love Thee always; and then do with me what Thou wilt.",
            meditationFr = "Considérons comment les disciples emportèrent le corps de Jésus pour l’ensevelir ; sa Sainte Mère l’accompagnait, et elle l’arrangea de ses propres mains dans le sépulcre. Ensuite on ferma l’entrée, et tous se retirèrent.\n\nAh ! mon Jésus, je baise la pierre qui Vous enferma dans ce tombeau. Mais Vous êtes ressuscité le troisième jour. Je Vous en prie, par Votre résurrection, fortifiez mon espérance, et faites qu’au dernier jour, je ressuscite pour aller au ciel, m’unir à Vous éternellement, Vous louer et Vous aimer à jamais.",
            versicleEn = "We adore Thee, O Christ, and we bless Thee.",
            responseEn = "Because by Thy holy Cross, Thou hast redeemed the world.",
            versicleFr = "Nous t’adorons, ô Christ, et nous te bénissons,",
            responseFr = "parce que tu as racheté le monde par ta sainte Croix.",
        ),
    )
}
