package com.ynotlabs.cathopedia.i18n

/**
 * The one list of languages the app knows about. Language pickers, the UI string
 * table, language labels and century formatting all read from here, so adding a
 * language is: add an entry, add its `StringsXX.kt` (generated by
 * tools/translate), and flip [available] once its content has been translated.
 *
 * Content that is missing in a language falls back to English at the SQL layer,
 * so an `available` language with partial content still renders every screen.
 */
class AppLanguage(
    val code: String,
    /** The language's name in itself — the picker's main label, never translated. */
    val nativeName: String,
    /** Shown in pickers as selectable. False = listed as "soon". */
    val available: Boolean,
    /** The language's name in the current UI language. */
    val localizedName: (Strings) -> String,
    /** The UI chrome table. A function so the tables initialise lazily. */
    val strings: () -> Strings,
    /** "1st century", "1er siècle", "5. Jahrhundert", "siglo V"… */
    val formatCentury: (Int) -> String,
)

object AppLanguages {
    val English = AppLanguage(
        code = "en", nativeName = "English", available = true,
        localizedName = { it.languageNameEnglish }, strings = { EN },
        formatCentury = { "${it}${englishOrdinalSuffix(it)} century" },
    )

    /** Every UI language, in picker order. */
    val all: List<AppLanguage> = listOf(
        English,
        AppLanguage(
            code = "fr", nativeName = "Français", available = true,
            localizedName = { it.languageNameFrench }, strings = { FR },
            formatCentury = { if (it == 1) "1er siècle" else "${it}e siècle" },
        ),
        AppLanguage(
            code = "it", nativeName = "Italiano", available = true,
            localizedName = { it.languageNameItalian }, strings = { IT },
            formatCentury = { "${roman(it)} secolo" },
        ),
        AppLanguage(
            code = "es", nativeName = "Español", available = false,
            localizedName = { it.languageNameSpanish }, strings = { ES },
            formatCentury = { "siglo ${roman(it)}" },
        ),
        AppLanguage(
            code = "pt", nativeName = "Português", available = false,
            localizedName = { it.languageNamePortuguese }, strings = { PT },
            formatCentury = { "século ${roman(it)}" },
        ),
        AppLanguage(
            code = "de", nativeName = "Deutsch", available = false,
            localizedName = { it.languageNameGerman }, strings = { DE },
            formatCentury = { "$it. Jahrhundert" },
        ),
        AppLanguage(
            code = "nl", nativeName = "Nederlands", available = false,
            localizedName = { it.languageNameDutch }, strings = { NL },
            formatCentury = { "${it}e eeuw" },
        ),
        AppLanguage(
            code = "pl", nativeName = "Polski", available = false,
            localizedName = { it.languageNamePolish }, strings = { PL },
            formatCentury = { "${roman(it)} wiek" },
        ),
        AppLanguage(
            code = "ta", nativeName = "தமிழ்", available = false,
            localizedName = { it.languageNameTamil }, strings = { TA },
            formatCentury = { "${it}ஆம் நூற்றாண்டு" },
        ),
    )

    /**
     * Content languages: every UI language plus Latin, which exists only for
     * prayers (and is never a UI language).
     */
    val contentCodes: List<String> = all.map { it.code } + "la"

    fun forCode(code: String): AppLanguage =
        all.firstOrNull { it.code.equals(code, ignoreCase = true) } ?: English

    /** The label for a prayer/content language chip, including Latin. */
    fun labelFor(code: String, s: Strings): String = when {
        code.equals("la", ignoreCase = true) -> s.prayerLanguageLa
        all.any { it.code.equals(code, ignoreCase = true) } -> forCode(code).localizedName(s)
        else -> code.uppercase()
    }
}

private fun englishOrdinalSuffix(n: Int): String =
    if (n % 100 in 11..13) "th" else when (n % 10) {
        1 -> "st"
        2 -> "nd"
        3 -> "rd"
        else -> "th"
    }

private fun roman(n: Int): String {
    val numerals = listOf(10 to "X", 9 to "IX", 5 to "V", 4 to "IV", 1 to "I")
    var rest = n
    return buildString {
        for ((value, symbol) in numerals) {
            while (rest >= value) {
                append(symbol)
                rest -= value
            }
        }
    }
}
