package com.ynotlabs.cathopedia.i18n

// GENERATED by tools/translate/translate.py — do not edit by hand.
// Machine translation (MACHINE_DRAFT); fix wording in tools/translate/state/ui.pt.json
// or the glossary, then re-run the tool.

/** Portuguese UI chrome. Any field missing here falls back to English. */
val PT: Strings = Strings().apply {
    vestmentTranslations = VESTMENT_TRANSLATIONS_PT
}
