package com.ynotlabs.cathopedia.i18n

// GENERATED by tools/translate/translate.py — do not edit by hand.
// Machine translation (MACHINE_DRAFT); fix wording in tools/translate/state/ui.de.json
// or the glossary, then re-run the tool.

/** German UI chrome. Any field missing here falls back to English. */
val DE: Strings = Strings().apply {
    vestmentTranslations = VESTMENT_TRANSLATIONS_DE
}
