package com.ynotlabs.cathopedia.i18n

// GENERATED by tools/translate/translate.py — do not edit by hand.
// Machine translation (MACHINE_DRAFT); fix wording in tools/translate/state/ui.nl.json
// or the glossary, then re-run the tool.

/** Dutch UI chrome. Any field missing here falls back to English. */
val NL: Strings = Strings().apply {
    vestmentTranslations = VESTMENT_TRANSLATIONS_NL
}
