package com.ynotlabs.cathopedia.i18n

// GENERATED by tools/translate/translate.py — do not edit by hand.

/** German translations for the structured Sacred Vestments reference content. */
internal val VESTMENT_TRANSLATIONS_DE: Map<String, String> = mapOf(
)
