package com.ynotlabs.cathopedia.liturgical

/** Expands the lectionary's leading book abbreviation without altering chapter or verse syntax. */
fun fullBookNameCitation(citation: String, language: String): String {
    val bookNames = when (language.lowercase()) {
        "fr" -> frenchBookNames
        "it" -> itBookNames
        "de" -> deBookNames
        "es" -> esBookNames
        "pt" -> ptBookNames
        "nl" -> nlBookNames
        // Polish lectionaries cite with the Biblia Tysiąclecia sigla rather than full names.
        "pl" -> plBookNames
        "ta" -> taBookNames
        else -> englishBookNames
    }
    val abbreviation = bookNames.keys
        .sortedByDescending(String::length)
        .firstOrNull { citation == it || citation.startsWith("$it ") }
        ?: return citation.replace("-", "–")
    return bookNames.getValue(abbreviation) + citation.removePrefix(abbreviation).replace("-", "–")
}

private val englishBookNames = mapOf(
    "Gn" to "Genesis",
    "Ex" to "Exodus",
    "Lv" to "Leviticus",
    "Nm" to "Numbers",
    "Dt" to "Deuteronomy",
    "Jos" to "Joshua",
    "Jgs" to "Judges",
    "Ru" to "Ruth",
    "1 Sm" to "1 Samuel",
    "2 Sm" to "2 Samuel",
    "1 Kgs" to "1 Kings",
    "2 Kgs" to "2 Kings",
    "1 Chr" to "1 Chronicles",
    "2 Chr" to "2 Chronicles",
    "Ezra" to "Ezra",
    "Neh" to "Nehemiah",
    "Tb" to "Tobit",
    "Jdt" to "Judith",
    "Est" to "Esther",
    "1 Mc" to "1 Maccabees",
    "2 Mc" to "2 Maccabees",
    "Jb" to "Job",
    "Ps" to "Psalms",
    "Prv" to "Proverbs",
    "Eccl" to "Ecclesiastes",
    "Sg" to "Song of Songs",
    "Wis" to "Wisdom",
    "Sir" to "Sirach",
    "Is" to "Isaiah",
    "Jer" to "Jeremiah",
    "Lam" to "Lamentations",
    "Bar" to "Baruch",
    "Ez" to "Ezekiel",
    "Dn" to "Daniel",
    "Hos" to "Hosea",
    "Jl" to "Joel",
    "Am" to "Amos",
    "Ob" to "Obadiah",
    "Jon" to "Jonah",
    "Mi" to "Micah",
    "Na" to "Nahum",
    "Hb" to "Habakkuk",
    "Zep" to "Zephaniah",
    "Hg" to "Haggai",
    "Zec" to "Zechariah",
    "Mal" to "Malachi",
    "Mt" to "Matthew",
    "Mk" to "Mark",
    "Lk" to "Luke",
    "Jn" to "John",
    "Acts" to "Acts of the Apostles",
    "Rom" to "Romans",
    "1 Cor" to "1 Corinthians",
    "2 Cor" to "2 Corinthians",
    "Gal" to "Galatians",
    "Eph" to "Ephesians",
    "Phil" to "Philippians",
    "Col" to "Colossians",
    "1 Thes" to "1 Thessalonians",
    "2 Thes" to "2 Thessalonians",
    "1 Tm" to "1 Timothy",
    "2 Tm" to "2 Timothy",
    "Ti" to "Titus",
    "Phlm" to "Philemon",
    "Heb" to "Hebrews",
    "Jas" to "James",
    "1 Pt" to "1 Peter",
    "2 Pt" to "2 Peter",
    "1 Jn" to "1 John",
    "2 Jn" to "2 John",
    "3 Jn" to "3 John",
    "Jude" to "Jude",
    "Rv" to "Revelation",
)

private val frenchBookNames = mapOf(
    "Gn" to "Genèse",
    "Ex" to "Exode",
    "Lv" to "Lévitique",
    "Nm" to "Nombres",
    "Dt" to "Deutéronome",
    "Jos" to "Josué",
    "Jgs" to "Juges",
    "Ru" to "Ruth",
    "1 Sm" to "1 Samuel",
    "2 Sm" to "2 Samuel",
    "1 Kgs" to "1 Rois",
    "2 Kgs" to "2 Rois",
    "1 Chr" to "1 Chroniques",
    "2 Chr" to "2 Chroniques",
    "Ezra" to "Esdras",
    "Neh" to "Néhémie",
    "Tb" to "Tobie",
    "Jdt" to "Judith",
    "Est" to "Esther",
    "1 Mc" to "1 Maccabées",
    "2 Mc" to "2 Maccabées",
    "Jb" to "Job",
    "Ps" to "Psaumes",
    "Prv" to "Proverbes",
    "Eccl" to "Qohélet",
    "Sg" to "Cantique des Cantiques",
    "Wis" to "Sagesse",
    "Sir" to "Ben Sira",
    "Is" to "Isaïe",
    "Jer" to "Jérémie",
    "Lam" to "Lamentations",
    "Bar" to "Baruch",
    "Ez" to "Ézéchiel",
    "Dn" to "Daniel",
    "Hos" to "Osée",
    "Jl" to "Joël",
    "Am" to "Amos",
    "Ob" to "Abdias",
    "Jon" to "Jonas",
    "Mi" to "Michée",
    "Na" to "Nahum",
    "Hb" to "Habaquq",
    "Zep" to "Sophonie",
    "Hg" to "Aggée",
    "Zec" to "Zacharie",
    "Mal" to "Malachie",
    "Mt" to "Matthieu",
    "Mk" to "Marc",
    "Lk" to "Luc",
    "Jn" to "Jean",
    "Acts" to "Actes des Apôtres",
    "Rom" to "Romains",
    "1 Cor" to "1 Corinthiens",
    "2 Cor" to "2 Corinthiens",
    "Gal" to "Galates",
    "Eph" to "Éphésiens",
    "Phil" to "Philippiens",
    "Col" to "Colossiens",
    "1 Thes" to "1 Thessaloniciens",
    "2 Thes" to "2 Thessaloniciens",
    "1 Tm" to "1 Timothée",
    "2 Tm" to "2 Timothée",
    "Ti" to "Tite",
    "Phlm" to "Philémon",
    "Heb" to "Hébreux",
    "Jas" to "Jacques",
    "1 Pt" to "1 Pierre",
    "2 Pt" to "2 Pierre",
    "1 Jn" to "1 Jean",
    "2 Jn" to "2 Jean",
    "3 Jn" to "3 Jean",
    "Jude" to "Jude",
    "Rv" to "Apocalypse",
)

private val itBookNames = mapOf(
    "Gn" to "Genesi",
    "Ex" to "Esodo",
    "Lv" to "Levitico",
    "Nm" to "Numeri",
    "Dt" to "Deuteronomio",
    "Jos" to "Giosuè",
    "Jgs" to "Giudici",
    "Ru" to "Rut",
    "1 Sm" to "1 Samuele",
    "2 Sm" to "2 Samuele",
    "1 Kgs" to "1 Re",
    "2 Kgs" to "2 Re",
    "1 Chr" to "1 Cronache",
    "2 Chr" to "2 Cronache",
    "Ezra" to "Esdra",
    "Neh" to "Neemia",
    "Tb" to "Tobia",
    "Jdt" to "Giuditta",
    "Est" to "Ester",
    "1 Mc" to "1 Maccabei",
    "2 Mc" to "2 Maccabei",
    "Jb" to "Giobbe",
    "Ps" to "Salmi",
    "Prv" to "Proverbi",
    "Eccl" to "Qoèlet",
    "Sg" to "Cantico dei Cantici",
    "Wis" to "Sapienza",
    "Sir" to "Siracide",
    "Is" to "Isaia",
    "Jer" to "Geremia",
    "Lam" to "Lamentazioni",
    "Bar" to "Baruc",
    "Ez" to "Ezechiele",
    "Dn" to "Daniele",
    "Hos" to "Osea",
    "Jl" to "Gioele",
    "Am" to "Amos",
    "Ob" to "Abdia",
    "Jon" to "Giona",
    "Mi" to "Michea",
    "Na" to "Naum",
    "Hb" to "Abacuc",
    "Zep" to "Sofonia",
    "Hg" to "Aggeo",
    "Zec" to "Zaccaria",
    "Mal" to "Malachia",
    "Mt" to "Matteo",
    "Mk" to "Marco",
    "Lk" to "Luca",
    "Jn" to "Giovanni",
    "Acts" to "Atti degli Apostoli",
    "Rom" to "Romani",
    "1 Cor" to "1 Corinzi",
    "2 Cor" to "2 Corinzi",
    "Gal" to "Galati",
    "Eph" to "Efesini",
    "Phil" to "Filippesi",
    "Col" to "Colossesi",
    "1 Thes" to "1 Tessalonicesi",
    "2 Thes" to "2 Tessalonicesi",
    "1 Tm" to "1 Timoteo",
    "2 Tm" to "2 Timoteo",
    "Ti" to "Tito",
    "Phlm" to "Filemone",
    "Heb" to "Ebrei",
    "Jas" to "Giacomo",
    "1 Pt" to "1 Pietro",
    "2 Pt" to "2 Pietro",
    "1 Jn" to "1 Giovanni",
    "2 Jn" to "2 Giovanni",
    "3 Jn" to "3 Giovanni",
    "Jude" to "Giuda",
    "Rv" to "Apocalisse",
)

private val deBookNames = mapOf(
    "Gn" to "Genesis",
    "Ex" to "Exodus",
    "Lv" to "Levitikus",
    "Nm" to "Numeri",
    "Dt" to "Deuteronomium",
    "Jos" to "Josua",
    "Jgs" to "Richter",
    "Ru" to "Rut",
    "1 Sm" to "1 Samuel",
    "2 Sm" to "2 Samuel",
    "1 Kgs" to "1 Könige",
    "2 Kgs" to "2 Könige",
    "1 Chr" to "1 Chronik",
    "2 Chr" to "2 Chronik",
    "Ezra" to "Esra",
    "Neh" to "Nehemia",
    "Tb" to "Tobit",
    "Jdt" to "Judit",
    "Est" to "Ester",
    "1 Mc" to "1 Makkabäer",
    "2 Mc" to "2 Makkabäer",
    "Jb" to "Ijob",
    "Ps" to "Psalm",
    "Prv" to "Sprichwörter",
    "Eccl" to "Kohelet",
    "Sg" to "Hohelied",
    "Wis" to "Weisheit",
    "Sir" to "Jesus Sirach",
    "Is" to "Jesaja",
    "Jer" to "Jeremia",
    "Lam" to "Klagelieder",
    "Bar" to "Baruch",
    "Ez" to "Ezechiel",
    "Dn" to "Daniel",
    "Hos" to "Hosea",
    "Jl" to "Joël",
    "Am" to "Amos",
    "Ob" to "Obadja",
    "Jon" to "Jona",
    "Mi" to "Micha",
    "Na" to "Nahum",
    "Hb" to "Habakuk",
    "Zep" to "Zefanja",
    "Hg" to "Haggai",
    "Zec" to "Sacharja",
    "Mal" to "Maleachi",
    "Mt" to "Matthäus",
    "Mk" to "Markus",
    "Lk" to "Lukas",
    "Jn" to "Johannes",
    "Acts" to "Apostelgeschichte",
    "Rom" to "Römer",
    "1 Cor" to "1 Korinther",
    "2 Cor" to "2 Korinther",
    "Gal" to "Galater",
    "Eph" to "Epheser",
    "Phil" to "Philipper",
    "Col" to "Kolosser",
    "1 Thes" to "1 Thessalonicher",
    "2 Thes" to "2 Thessalonicher",
    "1 Tm" to "1 Timotheus",
    "2 Tm" to "2 Timotheus",
    "Ti" to "Titus",
    "Phlm" to "Philemon",
    "Heb" to "Hebräer",
    "Jas" to "Jakobus",
    "1 Pt" to "1 Petrus",
    "2 Pt" to "2 Petrus",
    "1 Jn" to "1 Johannes",
    "2 Jn" to "2 Johannes",
    "3 Jn" to "3 Johannes",
    "Jude" to "Judas",
    "Rv" to "Offenbarung",
)

private val esBookNames = mapOf(
    "Gn" to "Génesis",
    "Ex" to "Éxodo",
    "Lv" to "Levítico",
    "Nm" to "Números",
    "Dt" to "Deuteronomio",
    "Jos" to "Josué",
    "Jgs" to "Jueces",
    "Ru" to "Rut",
    "1 Sm" to "1 Samuel",
    "2 Sm" to "2 Samuel",
    "1 Kgs" to "1 Reyes",
    "2 Kgs" to "2 Reyes",
    "1 Chr" to "1 Crónicas",
    "2 Chr" to "2 Crónicas",
    "Ezra" to "Esdras",
    "Neh" to "Nehemías",
    "Tb" to "Tobías",
    "Jdt" to "Judit",
    "Est" to "Ester",
    "1 Mc" to "1 Macabeos",
    "2 Mc" to "2 Macabeos",
    "Jb" to "Job",
    "Ps" to "Salmos",
    "Prv" to "Proverbios",
    "Eccl" to "Eclesiastés",
    "Sg" to "Cantar de los Cantares",
    "Wis" to "Sabiduría",
    "Sir" to "Eclesiástico",
    "Is" to "Isaías",
    "Jer" to "Jeremías",
    "Lam" to "Lamentaciones",
    "Bar" to "Baruc",
    "Ez" to "Ezequiel",
    "Dn" to "Daniel",
    "Hos" to "Oseas",
    "Jl" to "Joel",
    "Am" to "Amós",
    "Ob" to "Abdías",
    "Jon" to "Jonás",
    "Mi" to "Miqueas",
    "Na" to "Nahún",
    "Hb" to "Habacuc",
    "Zep" to "Sofonías",
    "Hg" to "Ageo",
    "Zec" to "Zacarías",
    "Mal" to "Malaquías",
    "Mt" to "Mateo",
    "Mk" to "Marcos",
    "Lk" to "Lucas",
    "Jn" to "Juan",
    "Acts" to "Hechos",
    "Rom" to "Romanos",
    "1 Cor" to "1 Corintios",
    "2 Cor" to "2 Corintios",
    "Gal" to "Gálatas",
    "Eph" to "Efesios",
    "Phil" to "Filipenses",
    "Col" to "Colosenses",
    "1 Thes" to "1 Tesalonicenses",
    "2 Thes" to "2 Tesalonicenses",
    "1 Tm" to "1 Timoteo",
    "2 Tm" to "2 Timoteo",
    "Ti" to "Tito",
    "Phlm" to "Filemón",
    "Heb" to "Hebreos",
    "Jas" to "Santiago",
    "1 Pt" to "1 Pedro",
    "2 Pt" to "2 Pedro",
    "1 Jn" to "1 Juan",
    "2 Jn" to "2 Juan",
    "3 Jn" to "3 Juan",
    "Jude" to "Judas",
    "Rv" to "Apocalipsis",
)

private val ptBookNames = mapOf(
    "Gn" to "Gênesis",
    "Ex" to "Êxodo",
    "Lv" to "Levítico",
    "Nm" to "Números",
    "Dt" to "Deuteronômio",
    "Jos" to "Josué",
    "Jgs" to "Juízes",
    "Ru" to "Rute",
    "1 Sm" to "1 Samuel",
    "2 Sm" to "2 Samuel",
    "1 Kgs" to "1 Reis",
    "2 Kgs" to "2 Reis",
    "1 Chr" to "1 Crônicas",
    "2 Chr" to "2 Crônicas",
    "Ezra" to "Esdras",
    "Neh" to "Neemias",
    "Tb" to "Tobias",
    "Jdt" to "Judite",
    "Est" to "Ester",
    "1 Mc" to "1 Macabeus",
    "2 Mc" to "2 Macabeus",
    "Jb" to "Jó",
    "Ps" to "Salmos",
    "Prv" to "Provérbios",
    "Eccl" to "Eclesiastes",
    "Sg" to "Cântico dos Cânticos",
    "Wis" to "Sabedoria",
    "Sir" to "Eclesiástico",
    "Is" to "Isaías",
    "Jer" to "Jeremias",
    "Lam" to "Lamentações",
    "Bar" to "Baruc",
    "Ez" to "Ezequiel",
    "Dn" to "Daniel",
    "Hos" to "Oseias",
    "Jl" to "Joel",
    "Am" to "Amós",
    "Ob" to "Abdias",
    "Jon" to "Jonas",
    "Mi" to "Miqueias",
    "Na" to "Naum",
    "Hb" to "Habacuc",
    "Zep" to "Sofonias",
    "Hg" to "Ageu",
    "Zec" to "Zacarias",
    "Mal" to "Malaquias",
    "Mt" to "Mateus",
    "Mk" to "Marcos",
    "Lk" to "Lucas",
    "Jn" to "João",
    "Acts" to "Atos dos Apóstolos",
    "Rom" to "Romanos",
    "1 Cor" to "1 Coríntios",
    "2 Cor" to "2 Coríntios",
    "Gal" to "Gálatas",
    "Eph" to "Efésios",
    "Phil" to "Filipenses",
    "Col" to "Colossenses",
    "1 Thes" to "1 Tessalonicenses",
    "2 Thes" to "2 Tessalonicenses",
    "1 Tm" to "1 Timóteo",
    "2 Tm" to "2 Timóteo",
    "Ti" to "Tito",
    "Phlm" to "Filêmon",
    "Heb" to "Hebreus",
    "Jas" to "Tiago",
    "1 Pt" to "1 Pedro",
    "2 Pt" to "2 Pedro",
    "1 Jn" to "1 João",
    "2 Jn" to "2 João",
    "3 Jn" to "3 João",
    "Jude" to "Judas",
    "Rv" to "Apocalipse",
)

private val nlBookNames = mapOf(
    "Gn" to "Genesis",
    "Ex" to "Exodus",
    "Lv" to "Leviticus",
    "Nm" to "Numeri",
    "Dt" to "Deuteronomium",
    "Jos" to "Jozua",
    "Jgs" to "Rechters",
    "Ru" to "Ruth",
    "1 Sm" to "1 Samuël",
    "2 Sm" to "2 Samuël",
    "1 Kgs" to "1 Koningen",
    "2 Kgs" to "2 Koningen",
    "1 Chr" to "1 Kronieken",
    "2 Chr" to "2 Kronieken",
    "Ezra" to "Ezra",
    "Neh" to "Nehemia",
    "Tb" to "Tobit",
    "Jdt" to "Judit",
    "Est" to "Ester",
    "1 Mc" to "1 Makkabeeën",
    "2 Mc" to "2 Makkabeeën",
    "Jb" to "Job",
    "Ps" to "Psalmen",
    "Prv" to "Spreuken",
    "Eccl" to "Prediker",
    "Sg" to "Hooglied",
    "Wis" to "Wijsheid",
    "Sir" to "Wijsheid van Jezus Sirach",
    "Is" to "Jesaja",
    "Jer" to "Jeremia",
    "Lam" to "Klaagliederen",
    "Bar" to "Baruch",
    "Ez" to "Ezechiël",
    "Dn" to "Daniël",
    "Hos" to "Hosea",
    "Jl" to "Joël",
    "Am" to "Amos",
    "Ob" to "Obadja",
    "Jon" to "Jona",
    "Mi" to "Micha",
    "Na" to "Nahum",
    "Hb" to "Habakuk",
    "Zep" to "Sefanja",
    "Hg" to "Haggai",
    "Zec" to "Zacharia",
    "Mal" to "Maleachi",
    "Mt" to "Matteüs",
    "Mk" to "Marcus",
    "Lk" to "Lucas",
    "Jn" to "Johannes",
    "Acts" to "Handelingen",
    "Rom" to "Romeinen",
    "1 Cor" to "1 Korintiërs",
    "2 Cor" to "2 Korintiërs",
    "Gal" to "Galaten",
    "Eph" to "Efeziërs",
    "Phil" to "Filippenzen",
    "Col" to "Kolossenzen",
    "1 Thes" to "1 Tessalonicenzen",
    "2 Thes" to "2 Tessalonicenzen",
    "1 Tm" to "1 Timoteüs",
    "2 Tm" to "2 Timoteüs",
    "Ti" to "Titus",
    "Phlm" to "Filemon",
    "Heb" to "Hebreeën",
    "Jas" to "Jakobus",
    "1 Pt" to "1 Petrus",
    "2 Pt" to "2 Petrus",
    "1 Jn" to "1 Johannes",
    "2 Jn" to "2 Johannes",
    "3 Jn" to "3 Johannes",
    "Jude" to "Judas",
    "Rv" to "Openbaring",
)

private val plBookNames = mapOf(
    "Gn" to "Rdz",
    "Ex" to "Wj",
    "Lv" to "Kpł",
    "Nm" to "Lb",
    "Dt" to "Pwt",
    "Jos" to "Joz",
    "Jgs" to "Sdz",
    "Ru" to "Rt",
    "1 Sm" to "1 Sm",
    "2 Sm" to "2 Sm",
    "1 Kgs" to "1 Krl",
    "2 Kgs" to "2 Krl",
    "1 Chr" to "1 Krn",
    "2 Chr" to "2 Krn",
    "Ezra" to "Ezd",
    "Neh" to "Ne",
    "Tb" to "Tb",
    "Jdt" to "Jdt",
    "Est" to "Est",
    "1 Mc" to "1 Mch",
    "2 Mc" to "2 Mch",
    "Jb" to "Hi",
    "Ps" to "Ps",
    "Prv" to "Prz",
    "Eccl" to "Koh",
    "Sg" to "Pnp",
    "Wis" to "Mdr",
    "Sir" to "Syr",
    "Is" to "Iz",
    "Jer" to "Jr",
    "Lam" to "Lm",
    "Bar" to "Ba",
    "Ez" to "Ez",
    "Dn" to "Dn",
    "Hos" to "Oz",
    "Jl" to "Jl",
    "Am" to "Am",
    "Ob" to "Ab",
    "Jon" to "Jon",
    "Mi" to "Mi",
    "Na" to "Na",
    "Hb" to "Ha",
    "Zep" to "So",
    "Hg" to "Ag",
    "Zec" to "Za",
    "Mal" to "Ml",
    "Mt" to "Mt",
    "Mk" to "Mk",
    "Lk" to "Łk",
    "Jn" to "J",
    "Acts" to "Dz",
    "Rom" to "Rz",
    "1 Cor" to "1 Kor",
    "2 Cor" to "2 Kor",
    "Gal" to "Ga",
    "Eph" to "Ef",
    "Phil" to "Flp",
    "Col" to "Kol",
    "1 Thes" to "1 Tes",
    "2 Thes" to "2 Tes",
    "1 Tm" to "1 Tm",
    "2 Tm" to "2 Tm",
    "Ti" to "Tt",
    "Phlm" to "Flm",
    "Heb" to "Hbr",
    "Jas" to "Jk",
    "1 Pt" to "1 P",
    "2 Pt" to "2 P",
    "1 Jn" to "1 J",
    "2 Jn" to "2 J",
    "3 Jn" to "3 J",
    "Jude" to "Jud",
    "Rv" to "Ap",
)

private val taBookNames = mapOf(
    "Gn" to "தொடக்க நூல்",
    "Ex" to "விடுதலைப் பயணம்",
    "Lv" to "லேவியர்",
    "Nm" to "எண்ணிக்கை",
    "Dt" to "இணைச் சட்டம்",
    "Jos" to "யோசுவா",
    "Jgs" to "நீதித் தலைவர்கள்",
    "Ru" to "ரூத்து",
    "1 Sm" to "1 சாமுவேல்",
    "2 Sm" to "2 சாமுவேல்",
    "1 Kgs" to "1 அரசர்கள்",
    "2 Kgs" to "2 அரசர்கள்",
    "1 Chr" to "1 குறிப்பேடு",
    "2 Chr" to "2 குறிப்பேடு",
    "Ezra" to "எஸ்ரா",
    "Neh" to "நெகேமியா",
    "Tb" to "தோபித்து",
    "Jdt" to "யூதித்து",
    "Est" to "எஸ்தர்",
    "1 Mc" to "1 மக்கபேயர்",
    "2 Mc" to "2 மக்கபேயர்",
    "Jb" to "யோபு",
    "Ps" to "திருப்பாடல்கள்",
    "Prv" to "நீதிமொழிகள்",
    "Eccl" to "சபை உரையாளர்",
    "Sg" to "இனிமைமிகு பாடல்",
    "Wis" to "சாலமோனின் ஞானம்",
    "Sir" to "சீராக்கின் ஞானம்",
    "Is" to "எசாயா",
    "Jer" to "எரேமியா",
    "Lam" to "புலம்பல்",
    "Bar" to "பாரூக்கு",
    "Ez" to "எசேக்கியேல்",
    "Dn" to "தானியேல்",
    "Hos" to "ஓசேயா",
    "Jl" to "யோவேல்",
    "Am" to "ஆமோஸ்",
    "Ob" to "ஒபதியா",
    "Jon" to "யோனா",
    "Mi" to "மீக்கா",
    "Na" to "நாகூம்",
    "Hb" to "அபக்கூக்கு",
    "Zep" to "செப்பனியா",
    "Hg" to "ஆகாய்",
    "Zec" to "செக்கரியா",
    "Mal" to "மலாக்கி",
    "Mt" to "மத்தேயு",
    "Mk" to "மாற்கு",
    "Lk" to "லூக்கா",
    "Jn" to "யோவான்",
    "Acts" to "திருத்தூதர் பணிகள்",
    "Rom" to "உரோமையர்",
    "1 Cor" to "1 கொரிந்தியர்",
    "2 Cor" to "2 கொரிந்தியர்",
    "Gal" to "கலாத்தியர்",
    "Eph" to "எபேசியர்",
    "Phil" to "பிலிப்பியர்",
    "Col" to "கொலோசையர்",
    "1 Thes" to "1 தெசலோனிக்கர்",
    "2 Thes" to "2 தெசலோனிக்கர்",
    "1 Tm" to "1 திமொத்தேயு",
    "2 Tm" to "2 திமொத்தேயு",
    "Ti" to "தீத்து",
    "Phlm" to "பிலமோன்",
    "Heb" to "எபிரேயர்",
    "Jas" to "யாக்கோபு",
    "1 Pt" to "1 பேதுரு",
    "2 Pt" to "2 பேதுரு",
    "1 Jn" to "1 யோவான்",
    "2 Jn" to "2 யோவான்",
    "3 Jn" to "3 யோவான்",
    "Jude" to "யூதா",
    "Rv" to "திருவெளிப்பாடு",
)
