package com.ynotlabs.cathopedia.liturgical

/** Expands the lectionary's leading book abbreviation without altering chapter or verse syntax. */
fun fullBookNameCitation(citation: String, language: String): String {
    val bookNames = if (language.equals("fr", ignoreCase = true)) frenchBookNames else englishBookNames
    val abbreviation = bookNames.keys
        .sortedByDescending(String::length)
        .firstOrNull { citation == it || citation.startsWith("$it ") }
        ?: return citation.replace("-", "–")
    return bookNames.getValue(abbreviation) + citation.removePrefix(abbreviation).replace("-", "–")
}

private val englishBookNames = mapOf(
    "Gn" to "Genesis",
    "Ex" to "Exodus",
    "Lv" to "Leviticus",
    "Nm" to "Numbers",
    "Dt" to "Deuteronomy",
    "Jos" to "Joshua",
    "Jgs" to "Judges",
    "Ru" to "Ruth",
    "1 Sm" to "1 Samuel",
    "2 Sm" to "2 Samuel",
    "1 Kgs" to "1 Kings",
    "2 Kgs" to "2 Kings",
    "1 Chr" to "1 Chronicles",
    "2 Chr" to "2 Chronicles",
    "Ezra" to "Ezra",
    "Neh" to "Nehemiah",
    "Tb" to "Tobit",
    "Jdt" to "Judith",
    "Est" to "Esther",
    "1 Mc" to "1 Maccabees",
    "2 Mc" to "2 Maccabees",
    "Jb" to "Job",
    "Ps" to "Psalms",
    "Prv" to "Proverbs",
    "Eccl" to "Ecclesiastes",
    "Sg" to "Song of Songs",
    "Wis" to "Wisdom",
    "Sir" to "Sirach",
    "Is" to "Isaiah",
    "Jer" to "Jeremiah",
    "Lam" to "Lamentations",
    "Bar" to "Baruch",
    "Ez" to "Ezekiel",
    "Dn" to "Daniel",
    "Hos" to "Hosea",
    "Jl" to "Joel",
    "Am" to "Amos",
    "Ob" to "Obadiah",
    "Jon" to "Jonah",
    "Mi" to "Micah",
    "Na" to "Nahum",
    "Hb" to "Habakkuk",
    "Zep" to "Zephaniah",
    "Hg" to "Haggai",
    "Zec" to "Zechariah",
    "Mal" to "Malachi",
    "Mt" to "Matthew",
    "Mk" to "Mark",
    "Lk" to "Luke",
    "Jn" to "John",
    "Acts" to "Acts of the Apostles",
    "Rom" to "Romans",
    "1 Cor" to "1 Corinthians",
    "2 Cor" to "2 Corinthians",
    "Gal" to "Galatians",
    "Eph" to "Ephesians",
    "Phil" to "Philippians",
    "Col" to "Colossians",
    "1 Thes" to "1 Thessalonians",
    "2 Thes" to "2 Thessalonians",
    "1 Tm" to "1 Timothy",
    "2 Tm" to "2 Timothy",
    "Ti" to "Titus",
    "Phlm" to "Philemon",
    "Heb" to "Hebrews",
    "Jas" to "James",
    "1 Pt" to "1 Peter",
    "2 Pt" to "2 Peter",
    "1 Jn" to "1 John",
    "2 Jn" to "2 John",
    "3 Jn" to "3 John",
    "Jude" to "Jude",
    "Rv" to "Revelation",
)

private val frenchBookNames = mapOf(
    "Gn" to "Genèse",
    "Ex" to "Exode",
    "Lv" to "Lévitique",
    "Nm" to "Nombres",
    "Dt" to "Deutéronome",
    "Jos" to "Josué",
    "Jgs" to "Juges",
    "Ru" to "Ruth",
    "1 Sm" to "1 Samuel",
    "2 Sm" to "2 Samuel",
    "1 Kgs" to "1 Rois",
    "2 Kgs" to "2 Rois",
    "1 Chr" to "1 Chroniques",
    "2 Chr" to "2 Chroniques",
    "Ezra" to "Esdras",
    "Neh" to "Néhémie",
    "Tb" to "Tobie",
    "Jdt" to "Judith",
    "Est" to "Esther",
    "1 Mc" to "1 Maccabées",
    "2 Mc" to "2 Maccabées",
    "Jb" to "Job",
    "Ps" to "Psaumes",
    "Prv" to "Proverbes",
    "Eccl" to "Qohélet",
    "Sg" to "Cantique des Cantiques",
    "Wis" to "Sagesse",
    "Sir" to "Ben Sira",
    "Is" to "Isaïe",
    "Jer" to "Jérémie",
    "Lam" to "Lamentations",
    "Bar" to "Baruch",
    "Ez" to "Ézéchiel",
    "Dn" to "Daniel",
    "Hos" to "Osée",
    "Jl" to "Joël",
    "Am" to "Amos",
    "Ob" to "Abdias",
    "Jon" to "Jonas",
    "Mi" to "Michée",
    "Na" to "Nahum",
    "Hb" to "Habaquq",
    "Zep" to "Sophonie",
    "Hg" to "Aggée",
    "Zec" to "Zacharie",
    "Mal" to "Malachie",
    "Mt" to "Matthieu",
    "Mk" to "Marc",
    "Lk" to "Luc",
    "Jn" to "Jean",
    "Acts" to "Actes des Apôtres",
    "Rom" to "Romains",
    "1 Cor" to "1 Corinthiens",
    "2 Cor" to "2 Corinthiens",
    "Gal" to "Galates",
    "Eph" to "Éphésiens",
    "Phil" to "Philippiens",
    "Col" to "Colossiens",
    "1 Thes" to "1 Thessaloniciens",
    "2 Thes" to "2 Thessaloniciens",
    "1 Tm" to "1 Timothée",
    "2 Tm" to "2 Timothée",
    "Ti" to "Tite",
    "Phlm" to "Philémon",
    "Heb" to "Hébreux",
    "Jas" to "Jacques",
    "1 Pt" to "1 Pierre",
    "2 Pt" to "2 Pierre",
    "1 Jn" to "1 Jean",
    "2 Jn" to "2 Jean",
    "3 Jn" to "3 Jean",
    "Jude" to "Jude",
    "Rv" to "Apocalypse",
)
